spring.application.name=DuAnCuoiMon
# Cong chay website Order Thuc An
server.port=2412
spring.datasource.url=jdbc:mysql://localhost:3306/du_an_cuoi_mon
spring.datasource.username=root
spring.datasource.password=huuy2412

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
